// Use around 26 characters max, including spaces, so it fits in one line

const char *subheadlines [] = {
   "KIDS ARE BACK IN SPACE",
   "HAMSTER FACE TRANSPLANTS",
   "MONKEYS ATE THE PRESIDENT",
   "ANGRY WIZARDS EXONERATED",
   "POLITICIANS STILL SUCK",
   "PEACE IN THE MIDDLE EARTH",
   "DRY ICE REPORTED TOO DRY",
   "JOBS ARE UNNESCESSARY",
   "POTS MAKE GOOD HATS",
   "CATS CAPABLE OF SYNC SWIM",
   "RED DEBUNKED AS BLUE",
   "THREE BLIND MICE CURED",
   "STILL NO FLYING CARS",
   "WIND BLOWS BACKWARDS",
   "VACATIONS IN COAL MINES"
};